package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.PasswordField;

public class loginController {
	@FXML
	private TextField txtUser;
	@FXML
	private PasswordField txtPassw;
	@FXML
	private Button btnLogin;
	@FXML
	private Button btnClose;

	// Event Listener on Button[#btnLogin].onAction
	@FXML
	public void clickLg(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnClose].onAction
	@FXML
	public void clickCl(ActionEvent event) {
		// TODO Autogenerated
	}
}
